DROP DATABASE IF EXISTS springbook;
CREATE DATABASE springbook;
USE springbook;

CREATE TABLE users (
    id VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(2) NOT NULL,
    PASSWORD VARCHAR(10) NOT NULL
);